#!/usr/bin/env bash
# Generated by build_tracker.py. Fetches every open-access PDF in the tracker.
set -u
cd "$(dirname "$0")"
[ -s 'P01_Suhaili_Julai_2022.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P01_Suhaili_Julai_2022.pdf' 'http://www.pertanika.upm.edu.my/resources/files/Pertanika%20PAPERS/JST%20Vol.%2030%20(1)%20Jan.%202022/32%20JST-2895-2021' || echo 'FAILED P01 http://www.pertanika.upm.edu.my/resources/files/Pertanika%20PAPERS/JST%20Vol.%2030%20(1)%20Jan.%202022/32%20JST-2895-2021'
[ -s 'P07_SantosJr_2024_Sensors.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P07_SantosJr_2024_Sensors.pdf' 'https://www.mdpi.com/1424-8220/24/12/3908/pdf' || echo 'FAILED P07 https://www.mdpi.com/1424-8220/24/12/3908/pdf'
[ -s 'P10_AlGailani_2025_JISIS.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P10_AlGailani_2025_JISIS.pdf' 'https://jisis.org/wp-content/uploads/2025/07/2025.I2.015.pdf' || echo 'FAILED P10 https://jisis.org/wp-content/uploads/2025/07/2025.I2.015.pdf'
[ -s 'P12_Franck_2024_Computers.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P12_Franck_2024_Computers.pdf' 'https://www.mdpi.com/2073-431X/13/1/9/pdf' || echo 'FAILED P12 https://www.mdpi.com/2073-431X/13/1/9/pdf'
[ -s 'P17_SHARMONY_2026.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P17_SHARMONY_2026.pdf' 'https://eprint.iacr.org/2026/1572.pdf' || echo 'FAILED P17 https://eprint.iacr.org/2026/1572.pdf'
[ -s 'P18_Gueron_Krasnov_2012.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P18_Gueron_Krasnov_2012.pdf' 'https://eprint.iacr.org/2012/371.pdf' || echo 'FAILED P18 https://eprint.iacr.org/2012/371.pdf'
[ -s 'P23_Saarinen_SLotH_2024.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P23_Saarinen_SLotH_2024.pdf' 'https://eprint.iacr.org/2024/367.pdf' || echo 'FAILED P23 https://eprint.iacr.org/2024/367.pdf'
[ -s 'P24_SPHINCSLET_2025.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P24_SPHINCSLET_2025.pdf' 'https://eprint.iacr.org/2025/621.pdf' || echo 'FAILED P24 https://eprint.iacr.org/2025/621.pdf'
[ -s 'P25_Trident_2026.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P25_Trident_2026.pdf' 'https://eprint.iacr.org/2026/837.pdf' || echo 'FAILED P25 https://eprint.iacr.org/2026/837.pdf'
[ -s 'P27_Amiet_SPHINCS256_2020.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P27_Amiet_SPHINCS256_2020.pdf' 'https://tches.iacr.org/index.php/TCHES/article/download/831/783/' || echo 'FAILED P27 https://tches.iacr.org/index.php/TCHES/article/download/831/783/'
[ -s 'P28_CryptoRV_2026.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P28_CryptoRV_2026.pdf' 'https://arxiv.org/pdf/2602.04415' || echo 'FAILED P28 https://arxiv.org/pdf/2602.04415'
[ -s 'P29_Parisi_OpenTitan_2024.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P29_Parisi_OpenTitan_2024.pdf' 'https://arxiv.org/pdf/2402.10395' || echo 'FAILED P29 https://arxiv.org/pdf/2402.10395'
[ -s 'P30_Kammoun_2021.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'P30_Kammoun_2021.pdf' 'https://jcoms.fesb.unist.hr/pdfs/v17n2_2021-0006_kammoun.pdf' || echo 'FAILED P30 https://jcoms.fesb.unist.hr/pdfs/v17n2_2021-0006_kammoun.pdf'
[ -s 'F05_Michail_HMAC_2012.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'F05_Michail_HMAC_2012.pdf' 'https://shura.shu.ac.uk/18348/1/harris.pdf' || echo 'FAILED F05 https://shura.shu.ac.uk/18348/1/harris.pdf'
[ -s 'F09_Garcia_2014.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'F09_Garcia_2014.pdf' 'https://ccc.inaoep.mx/~rcumplido/papers/2014-Garcia-A%20Compact%20FPGA.pdf' || echo 'FAILED F09 https://ccc.inaoep.mx/~rcumplido/papers/2014-Garcia-A%20Compact%20FPGA.pdf'
[ -s 'X04_US9632782_Intel_SHA2.pdf' ] || curl -fsSL -A 'Mozilla/5.0' -o 'X04_US9632782_Intel_SHA2.pdf' 'https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/9632782' || echo 'FAILED X04 https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/9632782'
